#!/usr/bin/env bash
# Builds bclibc's flat C ABI (bclibc_ffi.h / BCLIBCFFI_*) to a WebAssembly +
# Emscripten JS-glue module, for consumption from Dart web through
# lib/ffi/bclibc_ffi_web.dart (dart:js_interop, no Embind, no wasm_ffi).
#
# Usage:
#   bclibc/build_wasm.sh
#
# Self-installs a pinned Emscripten SDK into bclibc/tool/emsdk on first run
# (not vendored/submoduled — see .gitignore) if emcc isn't already on PATH.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# bclibc is a submodule shared across several sibling projects (dart-bclibc,
# js-ballistics, py-ballisticcalc, micropython-bclibc) and must stay usable
# standalone, so — like build.sh/build.bat — everything this script writes
# stays inside bclibc/ itself rather than reaching into whichever parent
# repo happens to embed it.
BCLIBC_SRC_DIR="${SCRIPT_DIR}/src"
BCLIBC_INCLUDE_DIR="${SCRIPT_DIR}/include"
GENERATED_DIR="${SCRIPT_DIR}/build/generated"
OUT_DIR="${SCRIPT_DIR}/build/web"

# Pinned for reproducible builds/CI. Bump deliberately, not via "latest".
EMSDK_VERSION="6.0.4"
EMSDK_DIR="${SCRIPT_DIR}/tool/emsdk"

if ! command -v emcc >/dev/null 2>&1; then
    if [[ ! -d "${EMSDK_DIR}" ]]; then
        echo "Installing emsdk ${EMSDK_VERSION} into ${EMSDK_DIR}..."
        mkdir -p "$(dirname "${EMSDK_DIR}")"
        git clone --depth 1 https://github.com/emscripten-core/emsdk.git "${EMSDK_DIR}"
    fi
    (cd "${EMSDK_DIR}" && ./emsdk install "${EMSDK_VERSION}" && ./emsdk activate "${EMSDK_VERSION}")
    # shellcheck disable=SC1091
    source "${EMSDK_DIR}/emsdk_env.sh"
fi

# version.h is normally generated by the native CMake build
# (configure_file in CMakeLists.txt); generate it here too if missing so
# this script can run standalone.
if [[ ! -f "${GENERATED_DIR}/bclibc/version.h" ]]; then
    mkdir -p "${GENERATED_DIR}/bclibc"
    VERSION_STR="$(git -C "${SCRIPT_DIR}" describe --tags --always 2>/dev/null || echo 0.0.0-dev)"
    VERSION_STR="${VERSION_STR#v}"
    IFS='.' read -r VMAJOR VMINOR VPATCH <<< "${VERSION_STR%%-*}"
    cat > "${GENERATED_DIR}/bclibc/version.h" <<EOF
#ifndef BCLIBC_VERSION_H
#define BCLIBC_VERSION_H
#define BCLIBC_VERSION_MAJOR ${VMAJOR:-0}
#define BCLIBC_VERSION_MINOR ${VMINOR:-0}
#define BCLIBC_VERSION_PATCH ${VPATCH:-0}
#define BCLIBC_VERSION "${VERSION_STR}"
#endif // BCLIBC_VERSION_H
EOF
fi

mkdir -p "${OUT_DIR}"

CORE_SOURCES=(
    "${BCLIBC_SRC_DIR}/base_types.cpp"
    "${BCLIBC_SRC_DIR}/engine.cpp"
    "${BCLIBC_SRC_DIR}/euler.cpp"
    "${BCLIBC_SRC_DIR}/interp.cpp"
    "${BCLIBC_SRC_DIR}/rk4.cpp"
    "${BCLIBC_SRC_DIR}/traj_data.cpp"
    "${BCLIBC_SRC_DIR}/traj_filter.cpp"
    "${BCLIBC_SRC_DIR}/velocity_verlet.cpp"
)

EXPORTED_FUNCTIONS='["_malloc","_free","_BCLIBCFFI_get_version","_BCLIBCFFI_find_apex","_BCLIBCFFI_find_max_range","_BCLIBCFFI_find_zero_angle","_BCLIBCFFI_integrate","_BCLIBCFFI_free_trajectory","_BCLIBCFFI_integrate_at","_BCLIBCFFI_find_apex_shot","_BCLIBCFFI_find_max_range_shot","_BCLIBCFFI_find_zero_angle_shot","_BCLIBCFFI_integrate_shot","_BCLIBCFFI_integrate_at_shot","_BCLIBCFFI_get_correction","_BCLIBCFFI_calculate_energy","_BCLIBCFFI_calculate_ogw","_BCLIBCFFI_get_layout"]'

# NOTE: no -sSINGLE_FILE — as of emsdk 6.0.3 it produces a wasm blob Chrome's
# WebAssembly.instantiate rejects ("invalid value type 0x1"), even though the
# same bytes work fine under Node. Two output files (.js + .wasm) is the
# standard, verified-working layout; ship them together as a pair.
echo "Building bclibc_ffi.js + bclibc_ffi.wasm (Emscripten JS-glue)..."
emcc \
    "${CORE_SOURCES[@]}" \
    "${BCLIBC_SRC_DIR}/ffi/bclibc_ffi.cpp" \
    -I"${BCLIBC_INCLUDE_DIR}" \
    -I"${GENERATED_DIR}" \
    -o "${OUT_DIR}/bclibc_ffi.js" \
    -sMODULARIZE=1 \
    -sEXPORT_NAME=bclibc_ffi \
    -sALLOW_MEMORY_GROWTH=1 \
    -sEXPORTED_RUNTIME_METHODS=HEAPU8,UTF8ToString,ccall,cwrap \
    -sEXPORTED_FUNCTIONS="${EXPORTED_FUNCTIONS}" \
    -fexceptions \
    -sDISABLE_EXCEPTION_CATCHING=0 \
    -O3

echo "Built ${OUT_DIR}/bclibc_ffi.js (+ .wasm)"
