/**
 * cxx_stubs.cpp
 *
 * Provides operator new / delete backed by MicroPython's heap allocator.
 * Required when linking C++ code that uses std::vector (and similar) into a
 * MicroPython native module (.mpy) where the standard C++ runtime is absent.
 *
 * Compiled with -fno-exceptions -fno-rtti, so no __gxx_personality_v0 or
 * _Unwind_* symbols are generated by the bclibc C++ sources.  Allocation
 * failures therefore call terminate() (→ abort/reset), which is the correct
 * behaviour on a microcontroller.
 */

extern "C" {
#include "py/dynruntime.h"
}

void *operator new(size_t size) {
    return m_malloc(size);
}

void *operator new[](size_t size) {
    return m_malloc(size);
}

void operator delete(void *ptr) noexcept {
    m_free(ptr);
}

void operator delete[](void *ptr) noexcept {
    m_free(ptr);
}

/* Sized deallocation (C++14) */
void operator delete(void *ptr, size_t) noexcept {
    m_free(ptr);
}

void operator delete[](void *ptr, size_t) noexcept {
    m_free(ptr);
}
