/**
 * cxx_stubs.cpp
 *
 * Provides operator new / delete backed by MicroPython's heap allocator.
 * Required when linking C++ code that uses std::vector (and similar) into a
 * MicroPython native module (.mpy) where the standard C++ runtime is absent.
 *
 * Compiled with -fno-exceptions -fno-rtti, so no __gxx_personality_v0 or
 * _Unwind_* symbols are generated by the bclibc C++ sources.  Allocation
 * failures therefore call terminate() (→ abort/reset), which is the correct
 * behaviour on a microcontroller.
 *
 * m_malloc/m_free are declared directly rather than via py/dynruntime.h to
 * avoid the -include build-$(ARCH)/.config.h dependency that dynruntime.h
 * pulls in through the command line (the .config.h is generated as part of
 * the C QSTR-preprocessing step and may not yet exist when C++ files are
 * compiled in parallel).
 */

#include <cstddef>
#include <csetjmp>

#include "bclibc/bclibc_throw.hpp"

extern "C" {
    void *m_malloc(size_t num_bytes);
    void  m_free(void *ptr);
}

// Global exception-transport state used by BCLIBC_THROW / ffi_call setjmp.
extern "C" {
    jmp_buf                   g_bclibc_jmp_buf;
    bclibc::BCLIBCThrowState  g_bclibc_throw_state;
}

void *operator new(size_t size) {
    return m_malloc(size);
}

void *operator new[](size_t size) {
    return m_malloc(size);
}

void operator delete(void *ptr) noexcept {
    m_free(ptr);
}

void operator delete[](void *ptr) noexcept {
    m_free(ptr);
}

/* Sized deallocation (C++14) */
void operator delete(void *ptr, size_t) noexcept {
    m_free(ptr);
}

void operator delete[](void *ptr, size_t) noexcept {
    m_free(ptr);
}
