/**
 * cxx_stubs.cpp
 *
 * Provides:
 *   1. operator new / delete backed by MicroPython's heap allocator.
 *   2. Minimal C stdlib (strlen, memcpy, memset, memmove, memcmp, errno)
 *      so that bclibc C++ code and bclibc_mp.c can resolve these symbols
 *      without pulling in a bare-metal libc (which is absent in natmod).
 *
 * Compiled with -fno-exceptions -fno-rtti, so no __gxx_personality_v0 or
 * _Unwind_* symbols are generated by the bclibc C++ sources.
 *
 * m_malloc/m_free are declared directly rather than via py/dynruntime.h to
 * avoid the -include build-$(ARCH)/.config.h dependency that dynruntime.h
 * pulls in through the command line (the .config.h is generated as part of
 * the C QSTR-preprocessing step and may not yet exist when C++ files are
 * compiled in parallel).
 *
 * The stdlib implementations below are compiled with -fno-builtin (added in
 * the Makefile rule for this file) to prevent the compiler from recognising
 * the patterns and emitting recursive calls to the same functions.
 */

#include <cstddef>
#include <csetjmp>

#include "bclibc/bclibc_throw.hpp"

extern "C" {
    void *m_malloc(size_t num_bytes);
    void  m_free(void *ptr);
}

// Global exception-transport state used by BCLIBC_THROW / ffi_call setjmp.
extern "C" {
    jmp_buf                   g_bclibc_jmp_buf;
    bclibc::BCLIBCThrowState  g_bclibc_throw_state;
}

void *operator new(size_t size) {
    return m_malloc(size);
}

void *operator new[](size_t size) {
    return m_malloc(size);
}

void operator delete(void *ptr) noexcept {
    m_free(ptr);
}

void operator delete[](void *ptr) noexcept {
    m_free(ptr);
}

/* Sized deallocation (C++14) */
void operator delete(void *ptr, size_t) noexcept {
    m_free(ptr);
}

void operator delete[](void *ptr, size_t) noexcept {
    m_free(ptr);
}

// ============================================================================
// Minimal C stdlib — not available in the natmod link environment.
// Compiled with -fno-builtin (see Makefile) so GCC won't replace these
// loop bodies with calls to the very functions being defined.
// ============================================================================

extern "C" {

size_t strlen(const char *s) {
    const char *p = s;
    while (*p) ++p;
    return (size_t)(p - s);
}

char *strncpy(char *dst, const char *src, size_t n) {
    char *d = dst;
    while (n > 0 && *src) { *d++ = *src++; --n; }
    while (n-- > 0) *d++ = '\0';
    return dst;
}

void *memcpy(void *dst, const void *src, size_t n) {
    unsigned char *d = (unsigned char *)dst;
    const unsigned char *s = (const unsigned char *)src;
    while (n--) *d++ = *s++;
    return dst;
}

void *memset(void *dst, int c, size_t n) {
    unsigned char *d = (unsigned char *)dst;
    while (n--) *d++ = (unsigned char)c;
    return dst;
}

void *memmove(void *dst, const void *src, size_t n) {
    unsigned char *d = (unsigned char *)dst;
    const unsigned char *s = (const unsigned char *)src;
    if (d < s) {
        while (n--) *d++ = *s++;
    } else {
        d += n; s += n;
        while (n--) *--d = *--s;
    }
    return dst;
}

int memcmp(const void *a, const void *b, size_t n) {
    const unsigned char *p = (const unsigned char *)a;
    const unsigned char *q = (const unsigned char *)b;
    while (n--) {
        if (*p != *q) return (int)*p - (int)*q;
        ++p; ++q;
    }
    return 0;
}

/* errno: both toolchains define errno as the macro (*__errno()), so writing
 * 'int errno = 0' would expand to a bogus function-pointer initialisation.
 * Remove the macro, then provide __errno() with a static backing int. */
#undef errno
static int s_errno;
int *__errno(void) { return &s_errno; }

// ============================================================================
// Newlib / libc syscall stubs — weak so toolchain-provided strong definitions
// (e.g. from libnosys.a) override them transparently.  Required when libm.a
// or libstdc++.a pulls in parts of newlib that reference these symbols.
// ============================================================================

void * __attribute__((weak)) _sbrk(int incr)
    { (void)incr; return (void *)-1; }

int __attribute__((weak)) _write(int fd, const char *buf, int len)
    { (void)fd; (void)buf; return len; }

int __attribute__((weak)) _close(int fd)
    { (void)fd; return -1; }

int __attribute__((weak)) _read(int fd, char *buf, int len)
    { (void)fd; (void)buf; (void)len; return -1; }

int __attribute__((weak)) _lseek(int fd, int off, int whence)
    { (void)fd; (void)off; (void)whence; return -1; }

int __attribute__((weak)) _isatty(int fd)
    { (void)fd; return 0; }

void __attribute__((weak)) _exit(int code)
    { (void)code; for (;;) {} }

void __attribute__((weak)) abort(void)
    { for (;;) {} }

/* C++ ABI stubs — weak so libsupc++.a can override if present */
int  __attribute__((weak)) __cxa_atexit(void (*)(void *), void *, void *)
    { return 0; }

void __attribute__((weak)) __cxa_pure_virtual(void)
    { for (;;) {} }

} // extern "C"
